name: Run Arbitrage

on:
  workflow_dispatch:
    inputs:
      buy_router:
        description: 'Buy router address'
        required: false
      sell_router:
        description: 'Sell router address'
        required: false
      token:
        description: 'Token address'
        required: false
      amount_in_human:
        description: 'Amount in human-readable format (e.g. 0.01 USDC.e)'
        required: false

  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes

jobs:
  run-arb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name:
