name: Run Arbitrage Bot

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run Arbitrage Script
         env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          AMOUNT_IN: ${{ secrets.AMOUNT_IN }}
          MIN_PROFIT_PERCENT: ${{ secrets.MIN_PROFIT_PERCENT }}
          BUY_ROUTER: ${{ secrets.BUY_ROUTER }}
          SELL_ROUTER: ${{ secrets.SELL_ROUTER }}
          TOKEN: ${{ secrets.TOKEN }}
        run: node scripts/arbitrage.js
