name: ARB Bot

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  run-arb:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Debug environment
      - name: Debug environment variables
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BUY_ROUTER: ${{ secrets.BUY_ROUTER }}
          SELL_ROUTER: ${{ secrets.SELL_ROUTER }}
          TOKEN: ${{ secrets.TOKEN }}
          AMOUNT_IN_HUMAN: ${{ secrets.AMOUNT_IN_HUMAN }}
          USDC_ADDRESS: ${{ secrets.USDC_ADDRESS }}
        run: |
          echo "🔍 Checking environment..."
          for VAR in RPC_URL PRIVATE_KEY BUY_ROUTER SELL_ROUTER TOKEN AMOUNT_IN_HUMAN USDC_ADDRESS; do
            if [ -z "${!VAR}" ]; then
              echo "❌ Missing: $VAR"
              EXIT=1
            else
              echo "✅ Found: $VAR"
            fi
          done
          if [ "$EXIT" = "1" ]; then
            echo "Missing one or more required environment variables."
            exit 1
          fi

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: npm install

      # 5️⃣ Run arbitrage bot
      - name: Run arbitrage
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          BUY_ROUTER: ${{ secrets.BUY_ROUTER }}
          SELL_ROUTER: ${{ secrets.SELL_ROUTER }}
          TOKEN: ${{ secrets.TOKEN }}
          AMOUNT_IN_HUMAN: ${{ secrets.AMOUNT_IN_HUMAN }}
          USDC_ADDRESS: ${{ secrets.USDC_ADDRESS }}
        run: node scripts/arbitrage.js
