name: Run Arbitrage

on:
  workflow_dispatch:
    inputs:
      buy_routers:
        description: 'JSON array of buy router addresses'
        required: false
      sell_routers:
        description: 'JSON array of sell router addresses'
        required: false
      token:
        description: 'Token address'
        required: false
      amount_in_human:
        description: 'Amount in human-readable format (e.g. 0.0001)'
        required: false

jobs:
  run-arb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run arbitrage script
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          BUY_ROUTERS: ${{ github.event.inputs.buy_routers || secrets.BUY_ROUTERS }}
          SELL_ROUTERS: ${{ github.event.inputs.sell_routers || secrets.SELL_ROUTERS }}
          TOKEN: ${{ github.event.inputs.token || secrets.TOKEN }}
          AMOUNT_IN_HUMAN: ${{ github.event.inputs.amount_in_human || secrets.AMOUNT_IN_HUMAN }}
        run: node scripts/arbitrage.js

  withdraw-profit:
    runs-on: ubuntu-latest
    needs: run-arb
    if: ${{ always() }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Withdraw profit
        env:
          RPC_URL: ${{ secrets.RPC_URL }}
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          TOKEN: ${{ secrets.TOKEN }}
        run: node scripts/withdraw.js
